//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineKredit.logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Einstellungen
    {
        public int IDEinstellungen { get; set; }
        public decimal NormalZins { get; set; }
        public decimal EffektiverZins { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
    }
}
